name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.9', '3.8', '3.7', '3.6']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: |
          python -m pip install --no-cache-dir -U pip setuptools wheel
          python -m pip install --no-cache-dir --editable .[dev]
      - name: Check types
        run: mypy -m sbumed_predictions_to_graph
      - name: Check style
        run: flake8 sbumed_predictions_to_graph.py
      - name: Run python tests
        run: pytest
